services:
  - type: web
    name: mtg-simulator-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    ignoredPaths:
      - frontend/**
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: ACCOUNT_ID
        sync: false
      - key: CF_ACCESS_KEY_ID
        sync: false
      - key: CF_SECRET_ACCESS_KEY
        sync: false
      - key: ENDPOINT
        sync: false
      - key: CF_ACCOUNT_API_TOKEN
        sync: false